### ISSUE TITLE
Crash when analysing huge organization

### ISSUE THREAD

**Issue by BBerastegui** [anshumanbh/git-all-secrets#5]
Hi !

I'm getting this crash when I try to run the tool over a "huge" org (>140 repositories). Just after:

`Scanning all org repositories now..This may take a while so please be patient
`

```
panic: exit status 1

goroutine 2727 [running]:
main.check(0x7c8460, 0xc4201e2020)
        /data/main.go:40 +0x174
main.runTrufflehog(0xc420164000, 0x1f, 0xc4201d7710, 0xf, 0x7ffce0564ec0, 0x6, 0x0, 0x0)
        /data/main.go:213 +0x1d1
main.runGitTools(0x6b46b2, 0x3, 0xc420164000, 0x1f, 0xc4203b51f0, 0xc4201d7710, 0xf, 0x7ffce0564ec0, 0x6)
        /data/main.go:233 +0x1af
created by main.scanorgrepos
        /data/main.go:379 +0x209
```

Any idea on how can I help to debug this crash?

**Comment by BBerastegui** [comment]
Sorry, dupped here: https://github.com/anshumanbh/git-all-secrets/issues/2
