### ISSUE TITLE
x509 Error when attempting to access Org

### ISSUE THREAD

**Issue by reconanalyst** [anshumanbh/git-all-secrets#51]
Fairly new to Github, so this may be an obvious fix, but would appreciate the assistance.
*****************
panic: Get https://api.github.com/orgs/hudgov/repos?per_page=10: x509: certificate signed by unknown authority

goroutine 1 [running]:
main.check(0x71f1e0, 0xc420301440)
        /go/src/github.com/anshumanbh/git-all-secrets/main.go:80 +0xec
main.cloneorgrepos(0x721cc0, 0xc420018028, 0xc42008eea0, 0x7ffc4d9ddf43, 0x6, 0x0, 0x0)
        /go/src/github.com/anshumanbh/git-all-secrets/main.go:158 +0x1b9
main.main()
        /go/src/github.com/anshumanbh/git-all-secrets/main.go:953 +0x2d6

**Comment by BlasterX24** [comment]
I m getting same error too!
